
#tomcat的接口
server:
  port: 8090
spring:
  application:
    name: customerFeign


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10



